[package]
name = "stream_examples"
version = "0.1.0"
edition = "2024"

[dependencies]
bon = "3.8.1"
bytes = "1.10.1"
futures = "0.3.31"
paste = "1.0.15"
proc_macros = { path = "../proc_macros" }
stream_utils = { path = "../stream_utils" }
tokio = { version = "1.48.0", features = ["full"] }
